name: icr_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=23.3.1
  - pytorch-cuda
  - pytorch=1.10.0
  - torchvision=0.11.0
  - torchaudio=0.10.0
  - pip:
    - deap==1.3.1
    - tqdm==4.62.3
    - scikit-learn==1.0.2
    - pillow>=8.0.1
    - notebook>=6.4.5
    - jupyterlab>=3.2.1
    - matplotlib==3.5.1
    - ipywidgets>=7.6.5
    - networkx==2.6.3
    - numpy==1.20.3
    - pandas==1.3.5
    - scipy==1.7.3
    - seaborn==0.11.2
    - pyro-ppl
    - tensorboard
    - numpyro