#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=04:00:00
#SBATCH --output=install_icr_env_%A.out
#SBATCH --error=install_icr_env_%A.err

module purge
module load 2022
module load Anaconda3/2022.05

conda env create -f icr_environment.yml
source activate icr_env

echo "Installing jax..."
conda install jaxlib=*=*cuda* jax cuda-nvcc -c conda-forge -c nvidia
pip install -e .