#!/bin/bash

#SBATCH --partition=genoa
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=16000M
#SBATCH --time=48:00:00
#SBATCH --output=./results_reduced_logs/7var-covid-logs-nsga2-logs/%x-%j.out
#SBATCH --error=./results_reduced_logs/7var-covid-logs-nsga2-logs/%x-%j.err

set -e

module purge
module load 2022
module load Anaconda3/2022.05

# Your job starts in the directory where you call sbatch
# SRC_DIR=/scratch-local/${USER}/DL1/assignment3

# Activate your environment
source activate icr-env
# source activate ./env

python scripts/run_experiments.py "$@"